language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: UFLsbvKLdSgLy8m7GE6cYk/p0odjUhZy2SjRhdWmUIwZP33/+VdcbnY306DcoUa8ceeMjfoRA/I24XYFoq/IX2WTTil/UNTprVq2yM9ic9DDWMsAZgH8pdpCL/hknZYlDinZibJoDVhBp7KMjlpNfKzdVvisfW0QbBl40LsvlkIdu2frgaXCfGgCsOlzYAr7CGGoJyya/dkhkXr5JduD+sOBDyLfyK5E9/JQW4ddHBRpYX7dSJv3CyvXGFfqjuiJ5o5RTFmVmHlg0E6Jj9ytbf+td+n4efb9UD/U2PNWnfcqCUMrawJOMY0qdMynimPHIRIra21P/DCgeJ36HuXVKDvSyFLRH0xV66V7Pqh4H914cIGfQAdHYr9JDEKoX0YY1Buyb0/fBsVF0B2ut6XEpFKWhm9TuT0E2A8aDV2v5/wJsqntHi0bpaxr5pKhZPZPbzHs1VETsSD1N+9lOG4dlQRjhfXntv/EzaGmysPpBxe8tiLympwTRGXirQGfXSeZrR/Cj5U4fdcBOJCFjGDmCuQsse0gyGlC+JNcyCi2o4hYD7Y5lZBK5R0yzrCYRJqa4FUCPsTqoNkpBzt3oQuLo4JS9HHHL4voy27QXC9MHMfyR/62hcvaTm2umvza9HN4cnENsOF0g8tlCJ7mlX9t+ZmI+50aX2n6DbkSJpGiRwo=